src/Entity/User.php
<?php

namespace App\Entity;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as assert;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: "utilisateur")]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    private ?string $cin;

    #[ORM\Column(length: 15)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    #[Assert\Length(
        min: 8,
        max: 8,
        exactMessage: "Le numéro de téléphone doit avoir exactement {{ limit }} chiffres",
        normalizer: "trim"
    )]
    private ?string $num_tel = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    #[Assert\Email]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    #[Assert\Length(
        min: 8,
        max: 255,
        exactMessage: "Le mot de passe doit avoir minimum {{ limit }} caractères",
        normalizer: "trim"
    )]
    private ?string $mdp = null;
    private $roles = [];
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "champ obligatoire")]
    private ?string $role = null;

    #[ORM\Column(name:"image",type:"string",length: 255,nullable:true)]
    
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCin(): ?string
    {
        return $this->cin;
    }

    public function setCin(string $cin): self
    {
        $this->cin = $cin;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(string $num_tel): static
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): static
    {
        $this->mdp = $mdp;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }
    // Implémentation de UserInterface
    public function getUserIdentifier(): ?string
    {
        return (string) $this->email;
    }


    public function getPassword(): ?string
    {
        return $this->mdp;
    }

    public function setPassword(string $mdp): static
    {
        $this->mdp = $mdp;

        return $this;
    }

    // Implémentation de UserInterface
    public function getSalt(): ?string
    {

        return null;
    }


    public function eraseCredentials(): void
    {
    }
    public function getUsername(): ?string
    {
        return (string) $this->email;
    }
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        if ($this->isAdmin()){

            $roles[] = 'ROLE_ADMIN';
        return array_unique($roles);
        }
        if ($this->isProprietaire()){
            $roles[] = 'ROLE_PROPRIETAIRE';
            return array_unique($roles);
        }
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }
    private $showPassword;

    public function getShowPassword(): ?bool
    {
        return $this->showPassword;
    }

    public function setShowPassword(bool $showPassword): self
    {
        $this->showPassword = $showPassword;

        return $this;
    }
    private $authCode;

    // [...]

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new \LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }
    
    // #[ORM\Column(name:"googleAuthenticatorSecret",type:"string",nullable:true)]
    // private $googleAuthenticatorSecret;

    

    // public function isGoogleAuthenticatorEnabled(): bool
    // {
    //     return null !== $this->googleAuthenticatorSecret;
    // }

    // public function getGoogleAuthenticatorUsername(): string
    // {
    //     return $this->prenom;
    // }

    // public function getGoogleAuthenticatorSecret(): ?string
    // {
    //     return $this->googleAuthenticatorSecret;
    // }

    // public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): void
    // {
    //     $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
    // }
    public function isAdmin(): bool
    {
        return $this->role === 'ADMIN';
    }
    public function isProprietaire(): bool
    {
        return $this->role === 'PROPRIETAIRE';
    }

    public function getImage(): ?string
    {
        return $this->image;
    }
    public function setImage(?string $image):static
    {
        $this->image=$image;
        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Mime\Email;
use Symfony\Component\Cache\Adapter\AdapterInterface;
use Symfony\Component\Security\Core\Exception\LockedException;

class SecurityController extends AbstractController
{  private $cache;

    public function __construct(AdapterInterface $cache)
    {
        $this->cache = $cache;
    }
    #[Route(path: '/login', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils, UserRepository $repo, Request $request): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();
        $userip = $request->getClientIp();
    
        // Fetch login attempts from cache
        $loginAttempts = $this->cache->getItem('login_attempts_' . $userip)->get();
    
        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
            'login_attempts' => $loginAttempts, // Pass login attempts to the template
        ]);
    }
    
    

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): Response
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
        return $this->render('base.html.twig');
    }
    #[Route(path: '/forgotpass', name: 'forgot_pass')]
    public function reinitPass(): Response
    {
        return $this->render('security/forgot_password.html.twig');
    }
    private function sendWelcomeEmail(User $user, MailerInterface $mailer): void
    {
        $email = (new Email())
            ->from('malekfeki18@gmail.com') // Set your email address here
            ->to($user->getEmail()) // Send email to the user
            ->subject('Welcome to Our Website')
            ->html('<p>Bonjour ' . $user->getNom() . ',<br>Bienvenue dans notre site web Sportify!</p>');
    
        $mailer->send($email);
    }
    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
// Hasher le mot de passe
$hashedPassword = password_hash($user->getPassword(),PASSWORD_DEFAULT);
$user->setMdp($hashedPassword);
            $entityManager->persist($user);
            $entityManager->flush();

             // Send welcome email
        $this->sendWelcomeEmail($user, $mailer);
        // Émettre une notification Mercure pour informer des nouveaux utilisateurs
        //$update = new Update(
        //    '/notifications/user-added',
        //    json_encode(['message' => 'New user added'])
        //);
        //$this->publisher->__invoke($update);
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }
   
}

templates/security/forgot_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post">
    

    {% if app.user %}
        <div class="mb-3">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}

    <h1 class="h3 mb-3 font-weight-normal">Réinitialiser votre mot de passe</h1>
        <label for="inputEmail">Email</label>
    <input type="email" value="{{ app.user.userIdentifier }}" name="email" id="inputEmail" class="form-control" autocomplete="email"  autofocus>
    <label for="inputPassword">Nouveau mot de passe</label>
    <input type="password"  name="password" id="inputPassword1" class="form-control" autocomplete="current-password"  autofocus>
    <label for="inputPassword">Confirmer mot de passe</label>
    <input type="password" name="confirm_password" id="inputPassword" class="form-control" autocomplete="current-password" >
    <input type="checkbox" id="showPasswordCheckbox"> Afficher le mot de passe <br>
    <input type="hidden" name="_csrf_token"
           value="{{ csrf_token('authenticate') }}"
    >

    <button class="btn btn-lg btn-primary" type="submit">
        Confirmer
    </button>
    
</form>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Sportify - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap-back.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style_back.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main-back.js"></script>
       <script>
            document.addEventListener('DOMContentLoaded', function () {
                var showPasswordCheckbox = document.getElementById('showPasswordCheckbox');
                var passwordField = document.getElementById('inputPassword');

                showPasswordCheckbox.addEventListener('change', function () {
                    if (this.checked) {
                        passwordField.type = 'text';
                    } else {
                        passwordField.type = 'password';
                    }
                });
            });
        </script>
   
</body>

</html>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block body %}
<form method="post">
    {% if error %}
        <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

    {% if app.user %}
        <div class="mb-3 text-center">
            You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
        </div>
    {% endif %}


    
</form>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Sportify - Bootstrap 5 Admin Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
        rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/bootstrap-back.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="css/style_back.css" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        {# <div id="spinner"
            class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div> #}
        <!-- Spinner End -->


        <!-- Sign In Start -->
<div class="container-fluid">
    <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
        <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-secondary rounded p-4 p-sm-5 my-4 mx-3">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <a href="index.html" class="">
                        <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Sportify</h3>
                    </a>
                    <h3>Sign In</h3>
                </div>
                <form method="post" action="{{ path('app_login') }}">
                    <label for="inputEmail">Email</label>  
                    <div class="form-floating mb-3">
                        <input type="email" value="{{ last_username }}" placeholder="Email" name="email" id="inputEmail" class="form-control" autocomplete="email"  autofocus>
                    </div>
                    <label for="inputPassword">Password</label> 
                    <div class="form-floating mb-4">
                        <input type="password" name="password" id="inputPassword2" placeholder="Password" class="form-control" >
                    </div>
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div class="form-check">
                            <input type="checkbox" id="showPasswordCheckbox2">
                            <label for="showPasswordCheckbox">Show Password</label>
                        </div>
                        <a href="{{path('forgot_password')}}">Forgot Password</a>
                    </div>
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                    <button type="submit" class="btn btn-primary py-3 w-100 mb-4" >Sign In</button>
                </form>
                <p class="text-center mb-0">Don't have an Account? <a href="{{path('app_user_new')}}">Sign Up</a></p>
            </div>
        </div>
    </div>
</div>
<!-- Sign In End -->

    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="lib/chart/chart.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="lib/tempusdominus/js/moment.min.js"></script>
    <script src="lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="js/main-back.js"></script>
 
           <script>
            document.addEventListener('DOMContentLoaded', function () {
                var showPasswordCheckbox = document.getElementById('showPasswordCheckbox2');
                var passwordField = document.getElementById('inputPassword2');

                showPasswordCheckbox.addEventListener('change', function () {
                    if (this.checked) {
                        passwordField.type = 'text';
                    } else {
                        passwordField.type = 'password';
                    }
                });
            });
        </script>
</body>

</html>
{% endblock %}

templates/security/profilUser.html.twig
<head>
<!-- Google Font -->
   
    <link href="{{asset('https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap')}}" rel="stylesheet">
    <link href="{{asset('https://fonts.googleapis.com/css?family=Oswald:300,400,500,600,700&display=swap')}}" rel="stylesheet">

 <!-- Css Styles -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/flaticon.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/owl.carousel.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/barfiller.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/magnific-popup.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/slicknav.min.css')}}" type="text/css">
    <link rel="stylesheet" href="{{asset('css/style.css')}}" type="text/css">
    
    <!-- Template Stylesheet 
    <link href="{{asset('css/style-profil.css')}}" rel="stylesheet">-->
       <style>
        .btn-primary {
            background-color: #FFA500; /* Orange background */
            border-color: #FFA500; /* Orange border */
        }

        .btn-primary:hover {
            background-color: #FFA500; /* Darker orange background on hover */
            border-color: #FFA500; /* Darker orange border on hover */
        }

        .btn-primary:focus {
            box-shadow: none; /* Remove box-shadow on focus */
        }
    </style>
</head>
{% block body %}
<div class="container-xl px-4 mt-4">
    <hr class="mt-0 mb-4">
    <div class="row">
        <div class="col-xl-4">
            <!-- Profile picture card -->
            <div class="card mb-4 mb-xl-0">
                {% if app.user %}
                <div class="mb-3 text-center" >
                    Welcome to your profile {{ app.user.nom }}
                </div>
                {% endif %}
                <div class="card-body text-center">
                    <!-- Profile picture image -->
                    <img class="img-account-profile rounded-circle mb-2" src="{{asset('img/profil-vide.png')}}" alt="">
                    <!-- Profile picture help block -->
                    <div class="small font-italic text-muted mb-4">JPG or PNG no larger than 5 MB</div>
                    <!-- Profile picture upload button -->
                    <form method="post" action="{{path('app_profile_edit', {'id': app.user.id })}}" enctype="multipart/form-data">
                    <!-- Hidden field for user ID -->
                    <input type="hidden" id="user_id" name="user_id" value="{{ app.user.id }}">
                     <div class="mb-3">
        <label class="form-label" for="inputProfilePicture">Upload Profile Picture</label>
        <input class="form-control" id="inputProfilePicture" type="file" name="profile_picture" value="{{ app.user.image }}">
    </div>
                    <button class="btn btn-primary" type="submit">Upload new image</button>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <!-- Account details card -->
            <div class="card mb-4">
                <div class="card-header">Account Details</div>
                <div class="card-body">
                    <form method="post" action="{{ path('app_profile_edit', {'id': app.user.id }) }}" enctype="multipart/form-data">
                        <!-- Form Group (username) -->
                        <div class="mb-3">
                            <label class="small mb-1" for="inputUsername">Email</label>
                            <input class="form-control" id="inputUsername" type="text" name="email" value="{{ app.user.username }}" >
                        </div>
                        <!-- Form Row -->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (first name) -->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputFirstName">Nom</label>
                                <input class="form-control" id="inputFirstName" type="text" name="nom" value="{{ app.user.nom }}" >
                            </div>
                            <!-- Form Group (last name) -->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputLastName">Prenom</label>
                                <input class="form-control" id="inputLastName" type="text" name="prenom" value="{{ app.user.prenom }}" >
                            </div>
                        </div>
                      
                        <!-- Form Row -->
                        <div class="row gx-3 mb-3">
                            <!-- Form Group (phone number) -->
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputPhone">Phone number</label>
                                <input class="form-control" id="inputPhone" type="tel" name="num_tel" value="{{ app.user.numTel }}" >
                            </div>
                            <div class="col-md-6">
                                <label class="small mb-1" for="inputPhone">CIN</label>
                                <input class="form-control" id="cin" type="cin" name="cin"value="{{ app.user.cin }}" >
                            </div>
                        </div>
                        <!-- Save changes button -->
                        <button class="btn btn-primary" type="submit">Save changes</button>
                         <a href="{{ path('frontend') }}" class="btn btn-primary">Return</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}